services:
  # 1. Baza Danych PostgreSQL
  - type: psql
    name: crownclinic-db
    plan: free
    databaseName: crownclinic_db
    user: crownclinic_user

  # 2. Backend
  - type: web
    name: crownclinic-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      # --- Zmienne do połączenia z bazą danych ---
      # Render automatycznie wypełni te wartości na podstawie usługi "crownclinic-db"
      - key: DB_HOST
        fromDatabase:
          name: crownclinic-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: crownclinic-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: crownclinic-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: crownclinic-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: crownclinic-db
          property: password

      # Mówimy Springowi, żeby użył profilu produkcyjnego
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      # Twoje sekrety (ustawisz je ręcznie w panelu Render)
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

  # 3. Frontend
  - type: web
    name: crownclinic-frontend
    env: docker
    repo: https://github.com/Widlakolak/crownclinic-frontend.git
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: crownclinic-backend
          property: url # Ta właściwość jest poprawna dla `fromService`
      # PORT jest ustawiany automatycznie przez Render dla aplikacji webowych,
      # więc nie musimy go definiować, ale zostawienie nie zaszkodzi.
      - key: PORT
        value: 8081